import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import { BASE, REPO_URL } from './base.mjs';

export default defineConfig({
  site: 'https://branes-ai.github.io',
  base: BASE,
  markdown: {
    remarkPlugins: [remarkMath],
    rehypePlugins: [rehypeKatex],
  },
  integrations: [
    starlight({
      title: 'Domain Flow Architecture',
      description:
        'A header-only C++20 library for domain flow architecture parallelizing compilers',
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: REPO_URL,
        },
      ],
      // No global editLink: src/content/docs/ is generated, so a global
      // baseUrl would 404. sync-content.mjs injects a per-page editUrl
      // pointing at each page's real source file instead.
      customCss: [
        'katex/dist/katex.min.css',
        './src/styles/custom.css',
      ],
      // Override <Head> to mount the SURE schedule animations (issue #64) — the
      // viewer + three.js load only on pages that embed a .schedule-anim div.
      components: {
        Head: './src/components/Head.astro',
      },
      sidebar: [
        {
          label: 'Getting Started',
          items: [{ autogenerate: { directory: 'getting-started' } }],
        },
        {
          label: 'Architecture',
          items: [{ autogenerate: { directory: 'architecture' } }],
        },
        {
          // Explicit order: the methodology of SURE construction (structure →
          // canonical operators → alignment/anchoring → schedules → worked
          // derivations). Not autogenerated.
          label: 'Theory',
          items: [
            { label: 'Tensor shape and structure', slug: 'theory/tensor-structure' },
            { label: 'Matmul and Tensormul', slug: 'theory/matmul' },
            { label: 'Aligning convex hulls', slug: 'theory/alignment-formalism' },
            { label: 'Geometric Transformation', slug: 'theory/anchoring' },
            { label: 'Pipeline Schedules', slug: 'theory/pipelining-schedules' },
            { label: 'Reduced Dependency Graph', slug: 'theory/reduced_dependency_graph' },
            { label: 'Conv2D', slug: 'theory/conv2d' },
            { label: 'QR Decomposition', slug: 'theory/qr-decomposition' },
            { label: 'LU factorization', slug: 'theory/lu' },
            { label: 'Neighbour pivoting', slug: 'theory/lu_neighbor' },
            { label: 'Cholesky factorization', slug: 'theory/cholesky' },
            { label: 'LDLᵀ factorization', slug: 'theory/ldlt' },
            { label: 'Triangular solve', slug: 'theory/trsolve' },
            { label: 'Matrix–vector derivations', slug: 'theory/matrix-vector-operators' },
          ],
        },
        {
          label: 'SURE Simulator',
          items: [{ autogenerate: { directory: 'simulator' } }],
        },
        {
          label: 'SURE Algorithms',
          items: [
            { label: 'Reading BLAS names', slug: 'sure-algorithms/blas-naming' },
            {
              // Pedagogical order (each operator builds on the previous), not
              // alphabetical; pages live under content/docs/sure-algorithms/.
              label: 'BLAS L1',
              items: [
                { label: 'axpy — αx + y', slug: 'sure-algorithms/blas-l1/axpy' },
                { label: 'dot — xᵀy', slug: 'sure-algorithms/blas-l1/dot' },
                { label: 'nrm2 — ‖x‖₂', slug: 'sure-algorithms/blas-l1/nrm2' },
                { label: 'asum — Σ|xᵢ|', slug: 'sure-algorithms/blas-l1/asum' },
                { label: 'scal — αx', slug: 'sure-algorithms/blas-l1/scal' },
                { label: 'swap — x ↔ y', slug: 'sure-algorithms/blas-l1/swap' },
                { label: 'copy — y ← x', slug: 'sure-algorithms/blas-l1/copy' },
                { label: 'rot — Givens', slug: 'sure-algorithms/blas-l1/rot' },
                { label: 'iamax — argmax|xᵢ|', slug: 'sure-algorithms/blas-l1/iamax' },
              ],
            },
            {
              // Level-2 (matrix-vector) operators. The pages live under Theory
              // (content/docs/theory/); these entries surface them in the catalog
              // nav alongside BLAS L1 by referencing their slugs.
              label: 'BLAS L2',
              items: [
                { label: 'gemv — αAx + βy', slug: 'sure-algorithms/blas-l2/gemv' },
                { label: 'ger — A += αxyᵀ', slug: 'sure-algorithms/blas-l2/ger' },
                { label: 'trmv — x := Tx', slug: 'sure-algorithms/blas-l2/trmv' },
                { label: 'symv — αAx + βy (sym)', slug: 'sure-algorithms/blas-l2/symv' },
                { label: 'syr — A += αxxᵀ', slug: 'sure-algorithms/blas-l2/syr' },
                { label: 'syr2 — A += α(xyᵀ+yxᵀ)', slug: 'sure-algorithms/blas-l2/syr2' },
              ],
            },
            {
              // Level-3 (matrix-matrix) operators.
              label: 'BLAS L3',
              items: [
                { label: 'gemm — αAB + βC', slug: 'sure-algorithms/blas-l3/gemm' },
                { label: 'syrk — αAAᵀ + βC', slug: 'sure-algorithms/blas-l3/syrk' },
                { label: 'syr2k — α(ABᵀ+BAᵀ) + βC', slug: 'sure-algorithms/blas-l3/syr2k' },
                { label: 'trmm — B := αTB', slug: 'sure-algorithms/blas-l3/trmm' },
                { label: 'symm — αAB + βC (sym)', slug: 'sure-algorithms/blas-l3/symm' },
              ],
            },
            {
              // Factorizations and solvers — lean reference (SURE + animation);
              // the derivations live under Theory.
              label: 'Linear Algebra',
              items: [
                { label: 'LU — A = LU', slug: 'sure-algorithms/linear-algebra/lu_decomposition' },
                { label: 'Cholesky — A = LLᵀ', slug: 'sure-algorithms/linear-algebra/cholesky_decomposition' },
                { label: 'LDLᵀ — A = LDLᵀ', slug: 'sure-algorithms/linear-algebra/ldlt_decomposition' },
                { label: 'Triangular solve — Lx = b', slug: 'sure-algorithms/linear-algebra/triangular_solve' },
              ],
            },
          ],
        },
        {
          label: 'Scaling & Distribution',
          items: [
            { label: 'The scale-out problem', slug: 'scaling' },
            { label: 'Tiling the index space', slug: 'scaling/tiling' },
            { label: 'Halo vs collective', slug: 'scaling/halo-vs-collective' },
            { label: 'Uniformization', slug: 'scaling/uniformization' },
            { label: 'The memory & communication hierarchy', slug: 'scaling/hierarchy' },
            { label: 'The Distributed Memory Machine', slug: 'scaling/dmm' },
            { label: 'Composition across the hierarchy', slug: 'scaling/composition' },
          ],
        },
        {
          label: 'Changelog',
          link: '/changelog/',
        },
      ],
    }),
  ],
});
